---
# Custom SSH accounts, should start from UID 8000.
bootstrap__active_extra_users:
  - { name: ivan,    uid: 8000, groups: ['docker', 'dockremap'], key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJBdm8y1PfWjT1pioaWJSZ2ETrUySb+dS/ifDg+VIpLY ivansete@status.im' }
  - { name: hanno,   uid: 8001, groups: ['docker', 'dockremap'], key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPoFi19qWnAkvVdfzQQrPtXBozfeBEekoycGKIEdZarj hanno@status.im' }

postgres_ha_service_name: 'nim-waku-store-db'
postgres_ha_cont_image: 'postgres:15.1-alpine'

postgres_ha_is_master: true
postgres_ha_replica_enabled: false
postgres_ha_replica_allowed_addresses: []

postgres_ha_admin_user: 'postgres'
postgres_ha_admin_pass: '{{lookup("bitwarden", "fleets/status/"+stage+"/db/admin")}}'

# Disable backups since we have multiple DCs
postgres_ha_backup: false
postgres_ha_backup_enabled: false

postgres_ha_databases:
  - name: 'nim-waku'
    user: 'nim-waku'
    pass: '{{lookup("bitwarden", "fleets/status/"+stage+"/db/nim-waku")}}'

# Avoid exceeding volume size with WAL log.
postgres_ha_alter_system_settings:
  checkpoint_timeout: '5min'
  max_wal_size: '1GB'
  min_wal_size: '80MB'
  max_locks_per_transaction: '2160'
  autovacuum_work_mem: '{{ ((ansible_memtotal_mb * 0.1) * 1000) | int }}' # kB

# Open PostgreSQL Port
open_ports_default_comment: '{{ postgres_ha_service_name }}'
open_ports_default_chain: 'SERVICES'
open_ports_default_protocol: 'tcp'
open_ports_list:
  - { port: '{{ postgres_ha_cont_port }}', ipset: '{{ env }}.{{ stage }}' }
